apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-stage
data:
  USER: root
  PASSWORD: {{ lookup('env', 'DB_PASSWORD')}}
  DATABASE_URL: mysql://{{ lookup('env', 'SQL_STAG') }}:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
  
  
  # DATABASE_URL: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC # caso esteja vinculando um clusterIP na m√£o
        